#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

case $BLOCK_BUTTON in
  1)  ;; # left click
  # 2) ;; # middle click
  # 3) ;; # right click
  # 4) ;;
  # 5) ;;
esac

full_charge_icon=
# charging_icon=ﮣ
charging_icon=
discharging_icon=
# discharging_icon=ﮤ

get_percent() {
  acpi | awk '{print $4}' | sed 's/,//g'
}

get_charging_status() {
  acpi | awk '{print $3}' | sed 's/,//g'
}


map_to_icon() {
  charging_status=$(get_charging_status)
  if [[ $charging_status == "Discharging" ]]; then
    echo "$discharging_icon"
    return
  fi
  echo "$charging_icon"
}

bat_percent=$(get_percent)
icon=$(map_to_icon)
echo "BAT: $bat_percent $icon"
