#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

computer_icon=

case $BLOCK_BUTTON in
  1) xterm -hold -e neofetch;; # left click
  2) ;; # middle click
  3) ;; # right click
  4) ;;
  5) ;;
esac

display() {
  echo "$computer_icon     "
}

display
